/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.OrderBLL;
import DAL.Order;
import DAL.OrderDetail;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author phamt
 */
public class OrderGUI extends javax.swing.JFrame {

    /**
     * Creates new form OrderGUI
     */
    private OrderBLL orderBLL = new OrderBLL();
    private ArrayList<Order> orderList = new ArrayList<>();

    private DefaultTableModel modelOrder = new DefaultTableModel();
    private DefaultTableModel modelDetail = new DefaultTableModel();
    private int[] headerOrder = {50, 150, 150, 150, 100, 100, 100};
    private int[] headerDetail = {100, 100, 200, 150, 150, 150};

    private String[] headerTitleOrder = {"ID", "Customer", "Date ", "Address", "City", "TotalQty", "TotalPrice"};
    private String[] headerTitleDetail = {"OrderID", "ProdID", "Name", "Qty", "Price", "Subtotal"};

    public OrderGUI() {
        initComponents();
        loadAllOrders();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        btnDateFrom = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        btnDateTo = new javax.swing.JButton();
        txtAdvance = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        btnAddOrder = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        txtProduct = new javax.swing.JTextField();
        btnSearchDetail = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();

        dateChooser1.setTextRefernce(txtFrom);

        dateChooser2.setForeground(new java.awt.Color(102, 102, 255));
        dateChooser2.setTextRefernce(txtTo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(34, 39, 54));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 594));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel15.setBackground(new java.awt.Color(42, 48, 66));
        jPanel15.setPreferredSize(new java.awt.Dimension(610, 50));

        jPanel12.setBackground(new java.awt.Color(42, 48, 66));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date From");
        jPanel12.add(jLabel3);

        txtFrom.setPreferredSize(new java.awt.Dimension(180, 25));
        jPanel12.add(txtFrom);

        btnDateFrom.setBackground(new java.awt.Color(98, 110, 212));
        btnDateFrom.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDateFrom.setForeground(new java.awt.Color(255, 255, 255));
        btnDateFrom.setText("Date");
        btnDateFrom.setPreferredSize(new java.awt.Dimension(60, 25));
        btnDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateFromActionPerformed(evt);
            }
        });
        jPanel12.add(btnDateFrom);

        jPanel15.add(jPanel12);

        jPanel16.setBackground(new java.awt.Color(42, 48, 66));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date To");
        jPanel16.add(jLabel4);

        txtTo.setPreferredSize(new java.awt.Dimension(180, 25));
        jPanel16.add(txtTo);

        btnDateTo.setBackground(new java.awt.Color(98, 110, 212));
        btnDateTo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDateTo.setForeground(new java.awt.Color(255, 255, 255));
        btnDateTo.setText("Date");
        btnDateTo.setPreferredSize(new java.awt.Dimension(60, 25));
        btnDateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateToActionPerformed(evt);
            }
        });
        jPanel16.add(btnDateTo);

        jPanel15.add(jPanel16);

        txtAdvance.setBackground(new java.awt.Color(98, 110, 212));
        txtAdvance.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtAdvance.setForeground(new java.awt.Color(255, 255, 255));
        txtAdvance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        txtAdvance.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel15.add(txtAdvance);

        jPanel5.add(jPanel15);

        jPanel23.setBackground(new java.awt.Color(42, 48, 66));
        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel23.setPreferredSize(new java.awt.Dimension(564, 50));
        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnAddOrder.setBackground(new java.awt.Color(98, 110, 212));
        btnAddOrder.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddOrder.setText("Add");
        btnAddOrder.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        jPanel23.add(btnAddOrder);

        btnEdit.setBackground(new java.awt.Color(98, 110, 212));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel23.add(btnEdit);

        btnDeleteOrder.setBackground(new java.awt.Color(98, 110, 212));
        btnDeleteOrder.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDeleteOrder.setText("Delete");
        btnDeleteOrder.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });
        jPanel23.add(btnDeleteOrder);

        btnReload.setBackground(new java.awt.Color(98, 110, 212));
        btnReload.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReload.setForeground(new java.awt.Color(255, 255, 255));
        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnReload.setText("Reload");
        btnReload.setPreferredSize(new java.awt.Dimension(100, 30));
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel23.add(btnReload);

        jPanel5.add(jPanel23);

        jPanel26.setBackground(new java.awt.Color(34, 39, 54));
        jPanel26.setPreferredSize(new java.awt.Dimension(268, 50));

        txtUser.setPreferredSize(new java.awt.Dimension(180, 25));
        jPanel26.add(txtUser);

        btnSearch.setBackground(new java.awt.Color(98, 110, 212));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setPreferredSize(new java.awt.Dimension(60, 25));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel26.add(btnSearch);

        jPanel5.add(jPanel26);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 500));

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Date", "Address", "City", "TotalQty", "TotalPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableOrder.setFillsViewportHeight(true);
        tableOrder.setGridColor(new java.awt.Color(0, 117, 217));
        tableOrder.setRowHeight(30);
        tableOrder.setSelectionBackground(new java.awt.Color(0, 117, 217));
        tableOrder.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableOrder.setShowGrid(true);
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableOrder);

        jPanel5.add(jScrollPane2);

        jPanel25.setBackground(new java.awt.Color(34, 39, 54));
        jPanel25.setPreferredSize(new java.awt.Dimension(268, 50));

        txtProduct.setPreferredSize(new java.awt.Dimension(180, 25));
        jPanel25.add(txtProduct);

        btnSearchDetail.setBackground(new java.awt.Color(98, 110, 212));
        btnSearchDetail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearchDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearchDetail.setPreferredSize(new java.awt.Dimension(60, 25));
        btnSearchDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetailActionPerformed(evt);
            }
        });
        jPanel25.add(btnSearchDetail);

        jPanel5.add(jPanel25);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(452, 500));

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Product ID", "Name", "Quantity", "Price", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDetail.setFillsViewportHeight(true);
        tableDetail.setGridColor(new java.awt.Color(0, 117, 217));
        tableDetail.setRowHeight(30);
        tableDetail.setSelectionBackground(new java.awt.Color(0, 117, 217));
        tableDetail.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableDetail.setShowGrid(true);
        tableDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDetail);

        jPanel5.add(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        int i = tableOrder.getSelectedRow();
        if (i != -1) {
            int id = Integer.parseInt(tableOrder.getModel().getValueAt(i, 0).toString());

            Order order = orderBLL.getOrderById(id);
            setDetailToTable(new ArrayList(order.getOrderDetails()));

        }
    }//GEN-LAST:event_tableOrderMouseClicked

    private void tableDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailMouseClicked

    }//GEN-LAST:event_tableDetailMouseClicked

    private void btnDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateFromActionPerformed
        dateChooser1.setVisible(true);

//        dateChooser1.showPopup(parent, 500, 300);
        dateChooser1.showPopup(this, 200,200);
    }//GEN-LAST:event_btnDateFromActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        loadAllOrders();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (!txtUser.getText().trim().isEmpty()) {
            orderList = orderBLL.findOrderByUserName(txtUser.getText());
            setOrderToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter your key search first");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetailActionPerformed
        int i = tableOrder.getSelectedRow();
        if (i != -1)
            if (!txtProduct.getText().trim().isEmpty()) {

                ArrayList<OrderDetail> odList = orderBLL.findOrderDetailByProductName(orderList.get(i), txtProduct.getText());

                this.setDetailToTable(odList);
            } else {
                JOptionPane.showMessageDialog(this, "Please enter your key search first");
            }
        else {
            JOptionPane.showMessageDialog(this, "Please choose record order first");
        }
    }//GEN-LAST:event_btnSearchDetailActionPerformed

    private void btnDateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateToActionPerformed
        dateChooser2.setVisible(true);

//        dateChooser1.showPopup(parent, 500, 300);
        dateChooser2.showPopup(this, 200, 200);
    }//GEN-LAST:event_btnDateToActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        AddOrderGUI addGUI = new AddOrderGUI(this);
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        int i = tableOrder.getSelectedRow();
        if (i != -1) {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure want to delete it", "Confirm Dialog", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(tableOrder.getModel().getValueAt(i, 0).toString());
                System.out.println(id);
                
                if(orderBLL.deleteOrderByID(i)){
                    JOptionPane.showMessageDialog(this, "Delete order successfully");
                    loadAllOrders();
                    this.setDetailToTable(new ArrayList(new Order().getOrderDetails()));
                }
                else{
                    JOptionPane.showMessageDialog(this,  "Delete order fail");
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please choose record you want to delete first");
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    public void loadAllOrders() {
        orderList = orderBLL.getAllOrders();
        if (orderList != null) {
            setOrderToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Cannot get list order!!!");
        }

    }

    public void setOrderToTable() {

        modelOrder = this.initTableModel(modelOrder, headerTitleOrder);

        for (Order order : orderList) {

            Vector row = new Vector();
            row.add(order.getOrderID());
            row.add(order.getUser().getFirstName() + " " + order.getUser().getLastName());
            row.add(order.getDate());
            row.add(order.getAddress());
            row.add(order.getCity());
            row.add(order.getTotalQty());
            row.add(order.getTotalPrice());

            modelOrder.addRow(row);

        }
        tableOrder.setModel(modelOrder);
        setColumnWidth(tableOrder, headerOrder);

    }

    public void setDetailToTable(ArrayList<OrderDetail> odList) {

        modelDetail = this.initTableModel(modelDetail, headerTitleDetail);

        for (OrderDetail od : odList) {
            Vector row = new Vector();
            row.add(od.getOrder().getOrderID());
            row.add(od.getProduct().getProductID());
            row.add(od.getProduct().getName());
            row.add(od.getQty());
            row.add(od.getPrice());
            row.add(od.getSubtotal());

            modelDetail.addRow(row);

        }
        tableDetail.setModel(modelDetail);
        setColumnWidth(tableDetail, headerDetail);

    }

    public DefaultTableModel initTableModel(DefaultTableModel model, String[] name) {
        Vector header = new Vector();
        for (String s : name) {
            header.add(s);
        }
        model = new DefaultTableModel(header, 0);
        return model;
    }

    public ArrayList<Order> getOrderList() {
        return orderList;
    }

    public void setColumnWidth(JTable tbl, int[] width) {
        tbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        TableColumnModel columnModel = tbl.getColumnModel();
        for (int i = 0; i < width.length; i++) {
            if (i < columnModel.getColumnCount()) {
                columnModel.getColumn(i).setMaxWidth(width[i]);
            } else {
                break;
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDateFrom;
    private javax.swing.JButton btnDateTo;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchDetail;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tableOrder;
    private javax.swing.JButton txtAdvance;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
