/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.UserBLL;
import DAL.User;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamt
 */
public class UserHelper extends javax.swing.JFrame {

    /**
     * Creates new form UserHelper
     */
    private AddOrderGUI addGUI;
    private EditOrderGUI editGUI;
    DefaultTableModel model;
    UserBLL userBLL = new UserBLL();
    User user = new User();
    
    ArrayList<User> userList = new ArrayList<>();
    
    public UserHelper() {
        initComponents();
    }
    
    public UserHelper(AddOrderGUI addGUI) {
        initComponents();
        this.addGUI = addGUI;
        this.loadAllCustomers();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public UserHelper(EditOrderGUI editGUI) {
        initComponents();
        this.editGUI = editGUI;
        this.loadAllCustomers();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 39, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 594));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setBackground(new java.awt.Color(34, 39, 54));
        jPanel25.setPreferredSize(new java.awt.Dimension(268, 50));

        txtSearch.setPreferredSize(new java.awt.Dimension(180, 25));
        jPanel25.add(txtSearch);

        jButton7.setBackground(new java.awt.Color(98, 110, 212));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel25.add(jButton7);

        jPanel1.add(jPanel25);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableUser.setFillsViewportHeight(true);
        tableUser.setGridColor(new java.awt.Color(0, 117, 217));
        tableUser.setRowHeight(30);
        tableUser.setSelectionBackground(new java.awt.Color(0, 117, 217));
        tableUser.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableUser.setShowGrid(true);
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUser);

        jPanel1.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        int i = tableUser.getSelectedRow();
        
        if (i != -1) {
            user = userList.get(i);
            
            if (addGUI != null) {
                addGUI.setUser(user);
            } else if (editGUI != null) {
                editGUI.setUser(user);
            }
            else{
                
            }
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_tableUserMouseClicked
    
    public void setValueToTable(ArrayList<User> userList) {
        model = (DefaultTableModel) tableUser.getModel();
        model.setRowCount(0);
        
        for (User user : userList) {
            Vector row = new Vector();
            row.add(user.getUserID());
            row.add(user.getFirstName());
            row.add(user.getLastName());
            row.add(user.getEmail());
            row.add(user.getPhone());
            
            model.addRow(row);
        }
        tableUser.setModel(model);
    }
    
    public void loadAllCustomers() {
        userList = userBLL.getAllCustomer();
        if (userList != null) {
            setValueToTable(userList);
        } else {
            JOptionPane.showMessageDialog(this, "Cannot get list product!!!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHelper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHelper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
